### PR TITLE
Add Vagrant configuration to mimic GitHub runners

### PR DESCRIPTION
**Pull request by konstruktoid**
This PR:
- adds `tox_env: py39-devel` to the GitHub workflow
- adds Vagrant configuration to mimic GitHub runners for local testing
- is related to #3291 

#### PR Type

- Feature Pull Request

### CODE REVIEW

**Comment by ssbarnea** [comment]
@konstruktoid What is really the purpose of this change? Is it to enable reproduction of platform specific errors when running from another platform?

I am bit reluctant to add a lot of code that is not really tested under CI but on the other hand we could enable zuul to run it if we want as we already use zuul on few other molecule plugins.

**Comment by konstruktoid** [comment]
The only actual CI change is the `tox` update, the Vagrant things is just about adding a easy (easier?) way to test on various platforms.

I was trying to catch something similar to https://github.com/ansible-community/molecule/issues/3291#issuecomment-971514289 but to no avail so far.

If this is too bloated, then feel free to close or let it exist so I (and more) can use the branch for testing.

**Comment by ssbarnea** [comment]
@tadeboro WDYT about this, should it go in or not?

**Comment by webknjaz** [comment]
I don't think it's reasonable for us to have this in the repository:
1) Having multiple copies of the same automation is hard to maintain/keep up-to-date
2) Adding such things means more maintenance burden because the contributors often don't maintain them
3) I've seen people adding extra ways of running tests as they like. The ones I saw in the past were Makefile and Dockerfile, and now it's Vagrantfile. The reality is that maintainers would only care about tox but still get "bug reports" about others that they may even know nothing about

**Comment by konstruktoid** [comment]
Reasonable input . Closing.

**Pull request closed without merging**
