### PR TITLE
Update pinned version for sh dependency

### LINKED ISSUE #2676: Broken dependency from pip's sh module
Hey guys,

there seem to be a fresh version of https://pypi.org/project/sh/ released 15h ago (at the time of writing this), which is a minor bump (despite being ~3 years in develop, but let's shelve that for now). The thing is it breaks molecule converge (and possibly other tasks as well). 
Or at least in the instances/config I'm using it in.

The case in question is trying to run DO provisioner using 2.x branch of molecule.
More details as per the ticket's template.

When force-installed the previous version: `pip install sh==1.12.14` it worked just fine.
Not sure if that's an issue of of molecule or that said package, but reporting here, since so far it seem like we're maybe trying to pass a variable in a format that is not well formatted, given the error message. But that's just a hunch.

# Issue Type

- Bug report

# Molecule and Ansible details

```
molecule==2.22
ansible==2.9.0

```

Molecule installation method: `pip`

Ansible installation method (one of): `pip`

# Desired Behavior

`molecule provisioning` ran OK

# Actual Behaviour

```
  'env': value u'/[a project]/provisioning/.env.yml' of env key 'MOLECULE_ENV_FILE' must be a str
```
please note I do not have the `.env.yml` file anywhere added explicitly in my provisioning folder (or subfolders for that matter).

### PR DESCRIPTION
**Pull request by robinmulder**
This works for Python 2 and 3.

Fixes #2676.

### CODE REVIEW

**Comment by markgoddard** [comment]
Great! Will there be a 2.x release containing this fix?

**Comment by eceglov** [comment]
> Great! Will there be a 2.x release containing this fix?

Also interested in the 2.x release..

**Comment by robinmulder** [comment]
@markgoddard @eceglov It doesn't seem likely judging by this [comment](https://github.com/ansible-community/molecule/issues/2676#issuecomment-620680302).

To add an alternative, for Molecule 2.x and Molecule 3.0.2 (the last version that supported Python 2.7) you could pin this version in your own dependencies with `sh == 1.12.14`. It will not be overruled by Molecule if you do that and Molecule will continue to work as before.

**Comment by markgoddard** [comment]
Thanks, that's what I've ended up doing. Seems a shame for everyone still using molecule & py2 to need to do that though.

**Comment by eceglov** [comment]
> @markgoddard @eceglov It doesn't seem likely judging by this [comment](https://github.com/ansible-community/molecule/issues/2676#issuecomment-620680302).
> 
> To add an alternative, for Molecule 2.x and Molecule 3.0.2 (the last version that supported Python 2.7) you could pin this version in your own dependencies with `sh == 1.12.14`. It will not be overruled by Molecule if you do that and Molecule will continue to work as before.

Already figure that out. Thanks anyway :)

**Comment by decentral1se** [comment]
If people want to see 2.x molecule fixes, the community needs to support the project. This work gets done by a **single** volunteer who is not supported financially by any stakeholders in this project (that's the real shame!) whatsoever to support this tool so many rely on. I still think there is a case for opening https://opencollective.com/ if it would be not be blocked from RedHat side (see https://github.com/ansible-community/molecule/pull/2445#issuecomment-561199653) and making it actually worth while doing this type of boring and tricky maintenance work as well as expanding the community maintenance team. Molecule isn't writing itself people. If RedHat isn't going to allow this why don't we make a community fork? I don't see people asking these questions but I think they are absolutely important to do so. If RedHat want to continue to state that they work with the community but do not meet the community halfway then it is just paying lip service to this ideals. Thanks for coming to my ted talk.

**Comment by ssbarnea** [comment]
@decentral1se AFAIK, there were a confusion that was clarified: me being listed there could have seen as problematic due to my Red Hat employment but I do not see any issue as having non-redhat employees listed. 

In fact, I would be more than happy to support you if you want to return to molecule. That confusion was also the reason why I supported the move of molecule from under ansible organization to ansible-community.

**Comment by decentral1se** [comment]
@ssbarnea what is problematic is that you work on this project completely unpaid for your work. Why can't the community support *you* and your clearly excellent ability to manage both the source code of this project, the infrastructural concerns of packaging and the social issues of community management. You're not a super hero (I wish!), you need a community to work with you. That means the support must be broadened but it can't *not* include you. That is not right given your dedication and contribution.

To clarify, I stopped maintaining this project because of the cognitive dissonance of RedHat running this community project but the community not being able to make decisions such as how to manage financial concerns and how to manage breaches of Code of Conduct on this online public space. My efforts were blocked or slowed down to such a pace such that the issue had passed and the damage was done.

I don't know how to resolve all this but I shouldn't be the one to design a grand image of the perfect molecule community ecosystem. I worry for the direction of this project without community governance which has real executive power to take community consensus decisions.

Again, if 10% of the companies using Molecule financially contributed to the community open collective then there would be a direction towards actual compensation for the hard work that happens here. RedHat has the public power to make that a reality. A single blog post would do it.

Like, seriously, if you stop volunteering to maintain this project, Molecule will die.

If that isn't concerning to end-users, I don't know what is.

**Comment by decentral1se** [comment]
Opened https://github.com/ansible-community/molecule/issues/2681 to create a space for this discussion beyond this ticket which was created for another purpose.

**Comment by gundalow** [comment]
@decentral1se Red Hat employees (such as myself and @ssbarnea) can't accept sponsorship for these projects.

Though you (@decentral1se) as welcome to add a GitHub sponsorship. 
Which we added in https://github.com/ansible-community/molecule/pull/2464, though was removed by yourself in https://github.com/ansible-community/molecule/pull/2481/. I'm happy for you to add yourself back in. (I didn't realise you'd removed yourself till now when I went looking).

Red Hat currently supports Molecule by:
* Providing hosting under the Community GitHub account, which helps promote Molecule
* Paying for CI
* providing @ssbarnea (and to a much lesser extend myself) time to work on this as part of their day job

The senior leadership at Ansible are aware that we need people added to this project. Molecule is important to Ansible, though at the moment, Collections is taking up everybody's time. 

I'm happy to chat 1:1 (email, video) with anybody about this, or anything else that's related to the wider Ansible project and its community.

**Pull request merged**
