### PR TITLE
Allow mixing links and inventory variables

### PR DESCRIPTION
**Pull request by cinek810**
Previous logic allowed either link or direct specification in molecule.yml, while it's very convenient to link to group_vars containing some common values and set other (specific to molecule test) as host_vars.

Fixes: #2759

### CODE REVIEW

**Comment by cinek810** [comment]
This is to fix the issue: https://github.com/ansible-community/molecule/issues/2759

**Comment by amarao** [comment]
Hello. It looks amazing and it fixing one of weak points of Molecule! I'm very excited to see it fixed.

Can you, please, add a few tests? It can quickly become messy (there is a lot of corner cases), and having some tests will helps to cover them all.

**Comment by cinek810** [comment]
Sure. Can you point me to an example commit I can follow preparing the tests?

**Comment by ssbarnea** [comment]
Can someone step in here to add some tests, without any tests I will likely close it.

**Comment by cinek810** [comment]
I someone can point me to a commit (or external link) where similar tests where added I'll work on that. I just don't have relevant experience.

**Comment by ssbarnea** [comment]
Can you point me to a minimal scenario that was failing before this change and that is working after it? ... that would be a test by itself.

**Comment by ssbarnea** [comment]
Closing this due to lack of updates.

**Comment by lifedanceman** [comment]
Hello! Are there any changes about the pull request?

**Comment by jub-ioki** [comment]
@ssbarnea , could we re-open this please? 
As for a minimal case where molecule fails without this code, here is one...
```
provisioner:
  name: ansible
  inventory:
    links:
      group_vars: ../../../../group_vars/
   host_vars:
      molecule-host1:
        enable_thing: true
platforms:
  - name: molecule-host1
```
In this case molecule will silently ignore host host_vars and `enable_thing` will not be `true` on `molecule-host1`.  This behavior *is* documented, the documentation has the following statement:

> You can use either hosts/group_vars/host_vars sections of inventory OR links. If you use both, links will win.

But that statement is buried pretty deeply in the documention, and there is no runtime error or warning.  We could add a warning for it, but better yet to allow both, which is exactly what this PR does.

**Pull request closed without merging**
