### PR TITLE
Suggest using python3 and pip3 in example docs

### PR DESCRIPTION
**Pull request by brianhelba**
Some common distros do not alias "pip" and "python" to Python 3 versions. This will encourage users following the examples to install and run Molecule with Python 3.

This does not change the actual support status of Python 2.

#### PR Type
- Docs Pull Request

### CODE REVIEW

**Comment by ssbarnea** [comment]
I am clearly in favour of python3 first approach as I plan to drop py2 support this yet. I am still not sure if we do have the pip3 everywhere where we have python3.

**Comment by manics** [comment]
Just a warning: I've seen reports elsewhere of virtualenvs which do not have the `python3`/`pip3` aliases. In this situation a user could inadvertently run a global `pip3` instead of the virtualenv `pip`.

**Comment by ssbarnea** [comment]
I am very aware of virtualenv, cli inconsistency but that can easily be avoided running `python3 -m virtualenv` or `python3 -m venv`. Also pip works as a module.

**Comment by brianhelba** [comment]
@ssbarnea Thanks for the review! I just added a new commit to address your feedback and rebased the branch to resolve a merge conflict.

**Pull request merged**
