### PR TITLE
Allow configuration of docker_network in platforms

### PR DESCRIPTION
**Pull request by actatux**
Map a list of docker_networks to [Ansible's docker_network module](https://docs.ansible.com/ansible/latest/modules/docker_network_module.html). This
change allows to define additional parameters, while the previous code
only allowed to define the name of the Docker network.

Keep backward compatibility if a network name is defined for the
platform, without a docker_network definition.

Example:
```
platforms:
  - name: instance1
    image: docker.io/pycontribs/centos:8
    docker_networks:
      - name: foo
        ipam_config:
          - subnet: "10.11.0.0/16"
            gateway: "10.11.0.254"
    networks:
      - name: foo
        ipv4_address: "10.11.0.1"
  - name: instance2
    image: docker.io/pycontribs/centos:8
    networks:
      - name: foo
        ipv4_address: "10.11.0.2"
  - name: instance3
    image: docker.io/pycontribs/centos:8
    networks:
      - name: bar
```
This will create 2 Docker networks `foo` and `bar`.
Docker network `foo` is created with a subnet 10.11.0.0/16 so we can define IP addresses for instance 1 and 2 and attach these interfaces to this network.
Docker network `bar` is created as previously.

Fixes: #1879

### CODE REVIEW

**Comment by actatux** [comment]
Related to #1879.

**Comment by actatux** [comment]
I only consider `labels` and `state` as internal defaults.
`docker_host`, `cacert_path`, `cert_path`, `key_path` and `tls_verify` were defaulting to [docker_network](https://docs.ansible.com/ansible/latest/modules/docker_network_module.html)'s default values, so I removed these.

**Comment by actatux** [comment]
Note the warning with this change:
```
    TASK [Delete docker network(s)] ************************************************
[WARNING]: Using a variable for a task's 'args' is unsafe in some situations
(see https://docs.ansible.com/ansible/devel/reference_appendices/faq.html#argsplat-unsafe)
    changed: [localhost] => (item=ice1-1)
    changed: [localhost] => (item=bar)
    changed: [localhost] => (item=ice2-1)

```

**Comment by actatux** [comment]
Hello @ssbarnea - does the new code answer your change request?

**Comment by ssbarnea** [comment]
recheck

**Pull request merged**
