### PR TITLE
Return to using rich.console for pytest output

### PR DESCRIPTION
**Pull request by davedittrich**
This proposed change reverts a change identified as the source of an output bug of `pytest` output during a `molecule verify` run in https://github.com/ansible-community/pytest-molecule/issues/95 (which is still open after >1 year).

Without the patch:

```
. . .
molecule/shared/tests/test_ip_in_issue.py::test_issue_file
PASSED [ 44%]

molecule/shared/tests/test_ip_in_issue.py::test_issue_d
PASSED [ 46%]

molecule/shared/tests/test_ip_in_issue.py::test_issue_d_interfaces
PASSED [ 48%]

molecule/shared/tests/test_ip_in_issue.py::test_issue_d_fingerprints
PASSED [ 51%]
. . .

```

With the patch:

```
. . .
molecule/shared/tests/test_ip_in_issue.py::test_issue_file[ansible:/debian_bullseye] PASSED [ 44%]
molecule/shared/tests/test_ip_in_issue.py::test_issue_d[ansible:/debian_bullseye] PASSED [ 46%]
molecule/shared/tests/test_ip_in_issue.py::test_issue_d_interfaces[ansible:/debian_bullseye] PASSED [ 48%]
molecule/shared/tests/test_ip_in_issue.py::test_issue_d_fingerprints[ansible:/debian_bullseye] PASSED [ 51%]
. . .
```

The only difference I can see is that when redirecting output to a file, the patched version includes ANSI color escape sequences, which could be avoided by detecting the presence of a TTY and setting `ANSIBLE_NOCOLOR`.

rich-patch

This may be a result of (or bug introduced by) the following code at the bottom of the patched file:

```
# Define ANSIBLE_FORCE_COLOR if markup is enabled and another value is not
# already given. This assures that Ansible subprocesses are still colored,
# even if they do not run with a real TTY.
if should_do_markup():
    os.environ["ANSIBLE_FORCE_COLOR"] = os.environ.get("ANSIBLE_FORCE_COLOR", "1")
```

I did not run this in VS Code, so I don't know what the runtime result of  `should_do_markup()` would return, but output for the general use case is broken without the patch.

### CODE REVIEW

**Comment by davedittrich** [comment]
Forgot to include this:

```
platform linux -- Python 3.9.13, pytest-7.1.3, pluggy-1.0.0 -- /home/dittrich/miniconda3/envs/utils/bin/python
using: pytest-7.1.3
setuptools registered plugins:
  pytest-ansible-2.3.0 at /home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/pytest_ansible/plugin.py
  pytest-metadata-2.0.2 at /home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/pytest_metadata/plugin.py
  pytest-testinfra-6.8.1.dev4+gd423e29 at /home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/testinfra/plugin.py
  pytest-html-3.1.1 at /home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/pytest_html/plugin.py
  pytest-molecule-2.0.1.dev8+g236ac70 at /home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/pytest_molecule/__init__.py
active plugins:
    140571456453264     : <_pytest.config.PytestPluginManager object at 0x7fd957ba3a90>
    pytestconfig        : <_pytest.config.Config object at 0x7fd9571725b0>
    stepwise            : None
    pytest_stepwise     : None
    cacheprovider       : None
    pytest_cacheprovider: None
    mark                : /home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/_pytest/mark/__init__.py
    main                : /home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/_pytest/main.py
    runner              : /home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/_pytest/runner.py
    fixtures            : /home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/_pytest/fixtures.py
    helpconfig          : /home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/_pytest/helpconfig.py
    python              : /home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/_pytest/python.py
    terminal            : /home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/_pytest/terminal.py
    debugging           : /home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/_pytest/debugging.py
    unittest            : /home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/_pytest/unittest.py
    capture             : /home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/_pytest/capture.py
    skipping            : /home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/_pytest/skipping.py
    legacypath          : /home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/_pytest/legacypath.py
    tmpdir              : /home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/_pytest/tmpdir.py
    monkeypatch         : /home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/_pytest/monkeypatch.py
    recwarn             : /home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/_pytest/recwarn.py
    pastebin            : /home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/_pytest/pastebin.py
    nose                : /home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/_pytest/nose.py
    assertion           : /home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/_pytest/assertion/__init__.py
    junitxml            : /home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/_pytest/junitxml.py
    doctest             : /home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/_pytest/doctest.py
    freeze_support      : /home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/_pytest/freeze_support.py
    setuponly           : /home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/_pytest/setuponly.py
    setupplan           : /home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/_pytest/setupplan.py
    warnings            : /home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/_pytest/warnings.py
    logging             : /home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/_pytest/logging.py
    reports             : /home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/_pytest/reports.py
    python_path         : /home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/_pytest/python_path.py
    unraisableexception : /home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/_pytest/unraisableexception.py
    threadexception     : /home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/_pytest/threadexception.py
    faulthandler        : /home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/_pytest/faulthandler.py
    pytest-ansible      : /home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/pytest_ansible/plugin.py
    metadata            : /home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/pytest_metadata/plugin.py
    pytest11.testinfra  : /home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/testinfra/plugin.py
    html                : /home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/pytest_html/plugin.py
    molecule            : /home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/pytest_molecule/__init__.py
    capturemanager      : <CaptureManager _method='fd' _global_capturing=<MultiCapture out=<FDCapture 1 oldfd=5 _state='suspended' tmpfile=<_io.TextIOWrapper name="<_io.FileIO name=6 mode='rb+' closefd=True>" mode='r+' encoding='utf-8'>> err=<FDCapture 2 oldfd=7 _state='suspended' tmpfile=<_io.TextIOWrapper name="<_io.FileIO name=8 mode='rb+' closefd=True>" mode='r+' encoding='utf-8'>> in_=<FDCapture 0 oldfd=3 _state='started' tmpfile=<_io.TextIOWrapper name='/dev/null' mode='r' encoding='UTF-8'>> _state='suspended' _in_suspended=False> _capture_fixture=None>
    /home/dittrich/code/davedittrich/utils/molecule/shared/tests/conftest.py: /home/dittrich/code/davedittrich/utils/molecule/shared/tests/conftest.py
    session             : <Session shared exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=0>
    ansible             : <pytest_ansible.plugin.PyTestAnsiblePlugin object at 0x7fd954d02130>
    legacypath-tmpdir   : <class '_pytest.legacypath.LegacyTmpdirPlugin'>
    terminalreporter    : <_pytest.terminal.TerminalReporter object at 0x7fd954d02760>
    logging-plugin      : <_pytest.logging.LoggingPlugin object at 0x7fd954d02b80>
    funcmanage          : <_pytest.fixtures.FixtureManager object at 0x7fd954d17a60>
metadata: {'Python': '3.9.13', 'Platform': 'Linux-5.18.0-kali7-amd64-x86_64-with-glibc2.34', 'Packages': {'pytest': '7.1.3', 'py': '1.11.0', 'pluggy': '1.0.0', 'molecule': '4.0.2.dev29'}, 'Plugins': {'ansible': '2.3.0', 'metadata': '2.0.2', 'testinfra': '6.8.1.dev4+gd423e29', 'html': '3.1.1', 'molecule': '2.0.1.dev8+g236ac70'}, 'Tools': {'ansible': '2.13.3'}, 'env': 'ANSIBLE_COLLECTIONS_PATH=/home/dittrich/.cache/ansible-compat/6fd897/collections:/home/dittrich/.cache/molecule/utils/delegated/collections:/home/dittrich/.ansible/collections:/usr/share/ansible/collections:/etc/ansible/collections ANSIBLE_CONFIG=/home/dittrich/.cache/molecule/utils/delegated/ansible.cfg ANSIBLE_FILTER_PLUGINS=/home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/molecule/provisioner/ansible/plugins/filter:/home/dittrich/.cache/molecule/utils/delegated/plugins/filter:/home/dittrich/code/davedittrich/utils/plugins/filter:/home/dittrich/.ansible/plugins/filter:/usr/share/ansible/plugins/filter ANSIBLE_FORCE_COLOR=True ANSIBLE_LIBRARY=/home/dittrich/miniconda3/envs/utils/lib/python3.9/site-packages/molecule/provisioner/ansible/plugins/modules:/home/dittrich/.cache/molecule/utils/delegated/library:/home/dittrich/code/davedittrich/utils/library:/home/dittrich/.ansible/plugins/modules:/usr/share/ansible/plugins/modules ANSIBLE_ROLES_PATH=/home/dittrich/.cache/ansible-compat/6fd897/roles:/home/dittrich/.cache/molecule/utils/delegated/roles:/home/dittrich/code/davedittrich:/home/dittrich/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles ANSIBLE_VERBOSITY=0 MOLECULE_DEBUG=False MOLECULE_DEPENDENCY_NAME=galaxy MOLECULE_DRIVER_NAME=docker MOLECULE_ENV_FILE=/home/dittrich/code/davedittrich/utils/.env.yml MOLECULE_EPHEMERAL_DIRECTORY=/home/dittrich/.cache/molecule/utils/delegated MOLECULE_FILE=/home/dittrich/.cache/molecule/utils/delegated/molecule.yml MOLECULE_INSTANCE_CONFIG=/home/dittrich/.cache/molecule/utils/delegated/instance_config.yml MOLECULE_INVENTORY_FILE=/home/dittrich/.cache/molecule/utils/delegated/inventory/ansible_inventory.yml MOLECULE_PROJECT_DIRECTORY=/home/dittrich/code/davedittrich/utils MOLECULE_PROVISIONER_NAME=ansible MOLECULE_SCENARIO_DIRECTORY=/home/dittrich/code/davedittrich/utils/molecule/ip_in_issue MOLECULE_SCENARIO_NAME=ip_in_issue MOLECULE_STATE_FILE=/home/dittrich/.cache/molecule/utils/delegated/state.yml MOLECULE_VERIFIER_NAME=testinfra MOLECULE_VERIFIER_TEST_DIRECTORY=/home/dittrich/code/davedittrich/utils/molecule/ip_in_issue/../shared/tests '}
ansible: 2.13.3
rootdir: /home/dittrich/code/davedittrich/utils/molecule/shared, configfile: pytest.ini
plugins: ansible-2.3.0, metadata-2.0.2, testinfra-6.8.1.dev4+gd423e29, html-3.1.1, molecule-2.0.1.dev8+g236ac70
```

**Review by ssbarnea — CHANGES_REQUESTED** [review]
What happens with pytest is not so important but doing this switch will likely break the capture feature in molecule itself, as that was
the reason I wrote `enrich`.

I am not sure if newer versions of rich addressed the original problem, but i kinda doubt. Shortly we should not do this without extra manual validation. If we do it, we likely also want to remove enrich completely as a dependency.

**Comment by davedittrich** [comment]
Thanks @ssbarnea for your response, but I'm a little confused. Output is broken in current `pytest`, and fixing that by reverting is being rejected because it might break "the capture feature"? I'm not entirely clear what that means, but it sounds like it might be the 'redirect feature' you mention in this open PR https://github.com/ansible-community/pytest-molecule/issues/95. Could  expand on the ramifications of 'losing the redirect feature' and its effect on `pytest` output. Perhaps point out to me in the code (file+lines) where this exists? I'd like to better understand the ramifications of reverting.

In looking into it *very* briefly, I could not identify where in the `Console` classes the extra newlines could be occurring, but I did note in `molecule` (which calls `pytest`, which runs these modules that produce the output getting corrupted) the code I included above that forces colorized output. Might that be causing the extra newlines bug (perhaps indirectly even)? You don't address that issue in your response. The nested shell calls certainly makes debugging these kinds of issues much more difficult.

Also, you are suggesting not moving forward with fixing this until more "manual validation" is done. What would such manual validation be? I don't know what the next step here should be.

Thanks for your input!

**Comment by davedittrich** [comment]
I just updated the branch for this PR and the `py39-devel` and `py310-devel` test runs are now failing on something that appears to be outside the scope of the PR changes. I don't recognize the failures and they are only on the `-devel` jobs. Could someone take a look at those failed runs and see if it is anything obvious? Thanks.

**Comment by zhan9san** [comment]
> I just updated the branch for this PR and the `py39-devel` and `py310-devel` test runs are now failing on something that appears to be outside the scope of the PR changes. I don't recognize the failures and they are only on the `-devel` jobs. Could someone take a look at those failed runs and see if it is anything obvious? Thanks.

The failed test is addressed in #3709

**Comment by davedittrich** [comment]
> The failed test is addressed in #3709

Ah! Thanks!

**Comment by ssbarnea** [comment]
> > I just updated the branch for this PR and the `py39-devel` and `py310-devel` test runs are now failing on something that appears to be outside the scope of the PR changes. I don't recognize the failures and they are only on the `-devel` jobs. Could someone take a look at those failed runs and see if it is anything obvious? Thanks.
> 
> The failed test is addressed in #3709

@zhan9san is right. I fixed it this time but it is up to each contributor to fix test regressions like this, usually in order to unblock testing of their on pull-requests. Nothing can be merged unless we pass the tests. Luckily for us, it is not so common.

**Comment by ssbarnea** [comment]
@davedittrich Can you please rebase it?

**Pull request closed without merging**
