### PR TITLE
Fix Sphinx config for `sphinx-ansible-theme` v0.8+

### PR DESCRIPTION
**Pull request by webknjaz**
The setup currently present on `main`, has an unconstrained dependency on `sphinx-ansible-theme`. As a result, when the theme was refactored, the RTD site pulled in a newer version that needed minor tweaks to work properly. The builds succeeded on RTD but it went unnoticed that the CSS files were no longer included. Note that the previous `latest` build (mapped to `master` / `main` branch) happened around 9 weeks ago — I don't know why, maybe a part of the automation is disabled.

This patch adds an upper boundary for the dependency and adjusts the Sphinx configuration according to how the theme is supposed to be used.

#### PR Type

- Bugfix Pull Request
- Docs Pull Request

### CODE REVIEW

**Review by gundalow — APPROVED** [review]
Thanks for digging into this.
+1 to merge once RTD has build has completed and looks OK.

**Review by ssbarnea — APPROVED** [review]
I still see that latest/stable link what does not work on RTD build but I suppose that is expected.

**Comment by webknjaz** [comment]
> I still see that latest/stable link what does not work on RTD build but I suppose that is expected.

Yes, I think these are provided by RTD on the build. And PR builds are slightly different because they are not meant to build multiple branches.

**Comment by webknjaz** [comment]
Urgh... I've been meaning to merge with a good commit message :(

**Pull request merged**
