### PR TITLE
Fixes around ansible-devel testing

### PR DESCRIPTION
**Pull request by ssbarnea**
Makes additional changes in order to test the new packaging while is developed
by @abadger

### CODE REVIEW

**Comment by felixfontein** [comment]
You should make clear whether you are talking about ansible-base's `devel` branch, or about ansible (as in ACD) - which doesn't have anything called "devel" AFAIK.

**Comment by cloudnull** [comment]
> You should make clear whether you are talking about ansible-base's `devel` branch, or about ansible (as in ACD) - which doesn't have anything called "devel" AFAIK.

While I approved the change, I too would like more details in the commit message regarding this change.

**Comment by gundalow** [comment]
Github.com/ansible/ansible = `ansible-base`
No such thing as ACD, it's called the (new) `ansible` package

**Comment by abadger** [comment]
Note that this will only work for a couple weeks.  I'll be removing the fedora people files once ansible-base 2.10 beta 1 and ansible-2.10 aloha 1 are available on pypi

**Comment by ssbarnea** [comment]
> Note that this will only work for a couple weeks. I'll be removing the fedora people files once ansible-base 2.10 beta 1 and ansible-2.10 aloha 1 are available on pypi

We will update it asap we have content on pypi. A termporary working hack is better then a broken CI/CD pipeline. I am afraid to keep the jobs disabled for a long as we may endup with code merged that break on 2.10

**Comment by ssbarnea** [comment]
recheck

**Pull request merged**
