### PR TITLE
Add article how to use molecule and why

### PR DESCRIPTION
**Pull request by ultral**
add  link to the article about testing Ansible via molecule according https://www.reddit.com/r/ansible/comments/hd1iph/ansible_tests_sloc_lessons_learned_1_start/fvj261c/

#### PR Type

- Docs Pull Request

### CODE REVIEW

**Comment by gundalow** [comment]
@ultral This is a great article. Thank you for sharing on Reddit, and adding it into the main docs.

Could you please drop me an email <mygithub handle> at redhat.com

**Comment by ssbarnea** [comment]
I really liked the article too and I now I am wondering how and I persuade @ultral to help me improve docs of molecule and ansible-lint. Both of them are in great need of better documentation and writing docs is not among my top skills.

**Comment by belfast77** [comment]
Agreed, really great. Any chance of getting this and other articles by @ultral published on the www.ansible.com/blog to make them more accessible (Draconian corporate proxies and all that) ?

**Comment by ultral** [comment]
> I really liked the article too and I now I am wondering how and I persuade @ultral to help me improve docs of molecule and ansible-lint. Both of them are in great need of better documentation and writing docs is not among my top skills.

Why not? let's try,

**Comment by ssbarnea** [comment]
@gundalow What do you think? Maybe we also need an "Ansible QA" category to describe the collection of tools used to test ansible code (not ansible iself).

**Comment by gundalow** [comment]
Having various types and formats of documentation sounds good. People learn in different ways.

**Pull request merged**
