### PR TITLE
Shell dependency: use proper lexical parsing

### PR DESCRIPTION
**Pull request by sio**
Shell dependency manager used simple splitting on whitespace for parsing command lines. That would lead to incorrect parsing and execution of more complex commands like `echo "hello world"`.

This PR introduces proper lexical parsing with shlex module from Python standard library. Unit tests and changelog entry are included.

#### PR Type

- Bugfix Pull Request

### CODE REVIEW

**Comment by ssbarnea** [comment]
@sio AFAIK we are already using `sh` library in other places in molecule and that had support for parsing shell. Not sure why we should re-implement it instead of assuring we re-use it from sh? Can you investigate this path?

**Comment by sio** [comment]
@ssbarnea, I've checked both [documentation] and [source code] for **sh** - and I don't see any parsing capabilities. **sh** expects lists of strings for command arguments, not unparsed strings. This is mentioned in their FAQ: [Why do my arguments need to be separate strings?](https://amoffat.github.io/sh/sections/faq.html?highlight=parsing#why-do-my-arguments-need-to-be-separate-strings)

Molecule shell dependency manager, on the other hand, [expects](https://molecule.readthedocs.io/en/stable/configuration.html#shell) an unparsed command line string from configuration. That means there must be some parsing logic, and there was previously - just not a very good one. This PR is literally an one-line change:

```diff
-        command_list = self.command.split(' ')
+        command_list = shlex.split(self.command)
```

Molecule currently fails to execute commands as simple as `echo "hello world"`, and I've encountered similar error in-the-wild. That's why I came here to propose a fix.

[documentation]: https://amoffat.github.io/sh/index.html
[source code]: https://github.com/amoffat/sh

**Comment by ssbarnea** [comment]
@sio I hope you are running molecule from master for development, so I can rely on early feedback from you regarding recent changes.

**Comment by sio** [comment]
@ssbarnea, I was running the stable version from PyPI until I've encountered this bug. Currently the problematic config works fine with molecule from `sio:shlex`, but I didn't include it into CI runs yet.  Latest `master` does not feel any different from 2.22 on a limited subset of configs I've tried.

I'm currently considering switching CI to use molecule from a specific git commit, but only until these changes make their way into the release.

**Comment by sio** [comment]
Thank you, @ssbarnea! This review process was a pleasure ^_^

**Pull request merged**
